### ISSUE TITLE
增加功能

### ISSUE THREAD

**Issue by xuq54007** [satisfywithmylife/skygate#1]
你好，你做的工作非常棒，是否考虑增加开盒子（collect treasure）和冒险（adventure）的相关签到功能，这两个也有奖励积分。

**Comment by satisfywithmylife** [comment]
这两个似乎需要钱包账户拥有官方的史莱姆nft，抱歉，我没有这个，所以无法测试这两个功能

**Comment by satisfywithmylife** [comment]
> 你好，你做的工作非常棒，是否考虑增加开盒子（collect treasure）和冒险（adventure）的相关签到功能，这两个也有奖励积分。


这两个似乎需要钱包账户拥有官方的史莱姆nft，抱歉，我没有这个，所以无法测试这两个功能

**Comment by xuq54007** [comment]
或许你可以买一个史莱姆，价格很便宜。

**Comment by satisfywithmylife** [comment]
> 或许你可以买一个史莱姆，价格很便宜。

已经增加对应功能
